### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by senselle** [eeeeeric/rSalvador#1]
Is it possible to install rSalvador on Mac OS?

**Comment by eeeeeric** [comment]
Hi, it is certainly possible - I know of at least one person that has successfully installed it on Mac.

I will look into adding instructions and a downloadable for the Mac in the near future.

**Comment by eeeeeric** [comment]
Hi, can you try installing this? [rsalvador_1.4.zip](https://github.com/eeeeeric/rSalvador/files/83827/rsalvador_1.4.zip) 

(You may need to rename the extension to .tgz from .zip, as GitHub doesn't allow that format).
```R CMD INSTALL rsalvador_1.4.tgz```

This required one small code change (Mac requires malloc/malloc.h, instead of just malloc.h).

**Comment by senselle** [comment]
Hi,
Thank you for the answer. I successfully installed this version. 
I found before a previous version (rSalvador1.3) and there was a problem with the installation. But now it works, so, I will try to use it in next few days. Thank you very much.

**Comment by eeeeeric** [comment]
Fix for compiling on Mac OS X systems in commit 870d6aa. A downloadable has been added to the 1.4 release.
