### ISSUE TITLE
error in mutation rate calculation

### ISSUE THREAD

**Issue by kriskris99** [eeeeeric/rSalvador#5]
Hi,
I have installed rSalvador on my Mac and using it to calculate mutation rate with a few of my previous experiments. I have mutation rates calculated manually for these and now I am reproducing the results using rSalvador.
Definitely so much easier and fast using rSalvador. However, while most of the results of my experiments are same with rSalvador, I figure there is something funny in few experiments.
I run this golden.benchmark.LD(selective_counts, original_cells) in R and then after few seconds I get mutation rate as 5e-07. I get the same value for a few other experiments whose colony counts are very different.
Please see attached. Am I doing something wrong here?
Thanks,
![screenshot 2018-12-13 at 14 28 09](https://user-images.githubusercontent.com/45852290/49945361-9e803100-fee4-11e8-82ab-215cc58e7f1a.png)

**Comment by eeeeeric** [comment]
To begin with, I give a verbal re-account of the experiment, to avoid
misunderstanding.

The experiment comprises eleven 2-ml cultures. From each culture a portion of
0.1 ml was taken to estimate the final cell population sizes. The variable
original_cells is the mean size of Nt:

```
> original_cells
 [1] 419272727 419272727 419272727 419272727 419272727 419272727 419272727
 [8] 419272727 419272727 419272727 419272727
```

So, theoretically, the mutant counts are not exact, because 95% of
each culture was utilized to determine the number of mutants in the
cultures. Those counts are in selective_counts

```
> selective_counts
 [1] 2801 2474 2905 5477 2590 1828 2116 6151 2933 4352 3207
```

But we assume that those counts are sufficiently accurate.

Therefore, to estimate the mean number of mutations per culture, one uses
the function newton.LD

```
> newton.LD(selective_counts)
 [1] 415.2472
```

To translate this to a mutation rate, one simply divides this by the mean
Nt, which is

```
> Nt=original_cells[1] > Nt
 [1] 419272727
```

and therefore the mutation rate is

```
> newton.LD(selective_counts)/Nt
 [1] 9.903987e-07
```

Now one can also obtain a 95% confidence interval for the mutation rate
as follows.

```
> confint.LD(selective_counts)/Nt
 [1] 8.213077e-07 1.143722e-06
```


At this point,  a natural question is whether it is necessary to use the
individual Nt values in the estimation process, which can be obtained
as follows.

```
> nonselective_counts/vol_plated/dilution_factor*original_volume
 [1] 4.02e+08 4.76e+08 4.44e+08 3.50e+08 4.68e+08 4.42e+08 3.14e+08 4.44e+08
 [9] 4.54e+08 4.04e+08 4.14e+08
```

The answer in general is "No." According to Zheng [Journal of Theoretical
Biology  401 (2016) 54-63]:
>     with N0=100, statistical biases caused by not considering the variability
>     in Nt are negligible for practical purposes.

In other words, it is theoretically possible to incorporate the individual
Nt values, but the impact will be small. In this particular case,
the mutation rate will be change to  9.627e-7 (vs. 9.90e-7). Figure 1
gives the log-likelihood function that incorporates all 11 individual
Nt values. Not surprisingly, this particular example confirms the claim
in Zheng (2016). R code and algorithms for doing this can be obtained
directly from the author. This algorithm is not part of rSalvador because
in practice it is extremely rare to measure Nt for all cultures, and also
because it is not necessary most of the time.

Finally, why `golden.benchmark.LD` does not work for this particular
example. That function was written for testing purposes only, as a
development tool. However, it accidentally escaped to the rSalvador manual.
The golden bisection search is not recommended for practical use, it was
intended as a testing tool. If the reader find it useful to have such a
capability, I can include better algorithms in future versions of rSalvador.

In summary, the experiment should be analyzed using `newton.LD`, not
`golden.benchmark.LD`. Finally, a cautionary note. The mutant counts are
quite large, e.g., 6151. Usually counting such a large number of mutants
is very tedious. And it is generally believed that counting more than 1000
mutants is an extremely challenging task.  I am assuming that those mutant
counts are reliable.

[fig1.pdf](https://github.com/eeeeeric/rSalvador/files/2678357/fig1.pdf)
[zheng2016b.pdf](https://github.com/eeeeeric/rSalvador/files/2678358/zheng2016b.pdf)

**Comment by kriskris99** [comment]
Hi, thanks so much for your detailed response. Makes sense and works fine now!
Very much appreciate that I could use rSalvador!
